version: '3'
services:
  java_app_sodemed:
    container_name: java_app_sodemed
    build: .
    ports:
      - "8888:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db_sodemed:3306/sodemed
      - DATABASE_USERNAME=root 
      - DATABASE_PASSWORD=
    depends_on:
      - java_db_sodemed
    volumes:
      - /mnt/docker-volumes/sodomed/image:/uploads
  
  java_db_sodemed:
    container_name: java_db_sodemed
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - /mnt/docker-volumes/sodomed/bd:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sodemed
      MYSQL_USER: tests
      MYSQL_PASSWORD: tests
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
    external: true
  
    