name: Build and Push Sodomed Images

on:
  push:
    branches:
      - master
    paths:
      - 'portal-admin-sodemed-develop/portal-admin-sodemed-develop/**'
      - 'portal-clients-sodemed-develop/portal-clients-sodemed-develop/**'
      - 'sodemed-monolito-develop/sodemed-monolito-develop/**'

jobs:
  build-admin:
    if: contains(github.event.head_commit.modified, 'portal-admin-sodemed-develop') || github.run_number == 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Admin
        uses: docker/build-push-action@v5
        with:
          context: ./portal-admin-sodemed-develop/portal-admin-sodemed-develop/
          file: ./portal-admin-sodemed-develop/portal-admin-sodemed-develop/dockerfile
          push: true
          tags: jhamfgit/sodomed-admin:latest

  build-clients:
    if: contains(github.event.head_commit.modified, 'portal-clients-sodemed-develop') || github.run_number == 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Clients
        uses: docker/build-push-action@v5
        with:
          context: ./portal-clients-sodemed-develop/portal-clients-sodemed-develop/
          file: ./portal-clients-sodemed-develop/portal-clients-sodemed-develop/dockerfile
          push: true
          tags: jhamfgit/sodomed-clients:latest

  build-monolito:
    if: contains(github.event.head_commit.modified, 'sodemed-monolito-develop') || github.run_number == 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Monolito
        uses: docker/build-push-action@v5
        with:
          context: ./sodemed-monolito-develop/sodemed-monolito-develop/
          file: ./sodemed-monolito-develop/sodemed-monolito-develop/dockerfile
          push: true
          tags: jhamfgit/sodomed-monolito:latest
